sudo: required
dist: trusty

language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
      key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    # install toolchains
    - gcc-4.9
    - g++-4.9
    - clang-3.8
    - libc++-dev
    # install dependencies
    - libphysfs-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
    - libsdl2-ttf-dev

before_install:
- sudo apt-get install -y --no-install-recommends doxygen valgrind graphviz
- if [ "$CC" -e "clang" ]; then 
      export CC="clang-3.8" CXX="clang++-3.8" CXXFLAGS="-ftemplate-depth=1024";
  else
      export CC="gcc-4.9" CXX="g++-4.9";
  fi
script:
- make all test -j4 

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bf24f1666021dc4df89a
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   false   # default: false
