os: Visual Studio 2014 CTP4

platform:
    - win32
    - x64
configuration:
    - Debug
    - Release

install:
    git submodule update --init --recursive

build:
    project: egoboo_vs13.sln

test_script:
    - ps: |
        $platform = $env:platform
        if ($platform -eq "Win32") { $platform = "x86" }
        vstest.console /Logger:Appveyor /Platform:$platform /inIsolation "product\egolib-tests\$env:configuration\$env:platform\egolib-tests.dll"

notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/5dcaa000a0f83715202f
      on_build_success: true
      on_build_failure: true
